### ISSUE TITLE
Performance Probleme bei großen Logfiles (entsprechend meist am Abend)

### ISSUE THREAD

**Issue by darkiop** [Mic-M/iobroker.logfile-script#5]
Hallo Mic, zur Vollständigkeit hier noch das Github issue, das Verhalten ist hier beschrieben:

https://forum.iobroker.net/topic/20202/javascript-adapter-stellt-f%C3%BCr-einen-kurzen-moment-den-dienst-ein
https://forum.iobroker.net/topic/13971/vorlage-log-datei-aufbereiten-f%C3%BCr-vis-javascript/65

Grüße

**Comment by totocotonio** [comment]
Hi Mic,
bei mir das gleiche Problem.
https://forum.iobroker.net/topic/20375/history-adapter-zeigt-fehler

Mein Javascript Adapter trieb die Last hoch.

**Comment by Mic-M** [comment]
Hi zusammen,
leider ein bekanntes Problem, wenn die Log-Datei aufgrund sehr vieler Log-Einträge zu groß wird.
Wurde auch hier diskutiert: https://forum.iobroker.net/post/200605
Das Konzept des Scripts müsste umgestellt werden, also auslesen als "Stream".
Im Moment habe ich keine Lösung für Euch mangels Zeit.

**Comment by Mic-M** [comment]
Ist nun hoffentlich gelöst, ich habe das Script hierzu komplett umgestellt, siehe auch [ioBroker-Forum](https://forum.iobroker.net/post/283541). 
Script ist in 1.0 **alpha**, also erst mal zum Testen. Hier der [Link zum Script](https://github.com/Mic-M/iobroker.logfile-script/blob/master/iobroker_logfile-script.js).
